[package]
name = "sawit"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sawit"
path = "src/main.rs"

[[bin]]
name = "saw"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
notify = "8.2.0"
